# Generated by Django 3.1 on 2020-08-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boastroast',
            name='totalvote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
