# Generated by Django 3.1 on 2020-08-19 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_app', '0002_boastroast_totalvote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boastroast',
            old_name='totalvote',
            new_name='totalvotes',
        ),
    ]
